(in-package :erlang-term-test)

(in-suite optima-patterns)

(test erlang-string-pattern
  (is-true (match (list)
             ((erlang-string "hello") nil)
             ((erlang-string "") t)))
  (is-true (match (list 104 101 108 108 111)
             ((list 1 2 3) nil)
             ((erlang-string "") nil)
             ((erlang-string "hello") t)))
  )

(test tuple-pattern
  (is-true (match (tuple)
             ((tuple x) x)
             ((tuple 1 2) nil)
             ((tuple) t)))
  (is-true (match (tuple 1 2 3)
             ((tuple 1 2 2) nil)
             ((tuple) nil)
             ((tuple a b) (+ a b))
             ((tuple a b c d) (+ a b c d))
             ((tuple 1 2 3) t)))
  (is-true (match (tuple 1 2 3)
             ((tuple a b) (+ a b))
             ((tuple a b c d) (+ a b c d))
             ((tuple a b c)
              (progn a b c t))))
  (is-true (match (tuple (list 1 2) (tuple 3 4) 5)
             ((tuple (list a b) (tuple c d) 5)
              (progn a b c d t))))
  )
